### ISSUE TITLE
Not an issue! A thank you word for making this repo!

### ISSUE THREAD

**Issue by loneicewolf** [LLLgoyour/Java-fastIO-template#1]
Hello! I sometimes when find a very great repo (like this one) write a issue to show my appreciation!
## Thanks for making this repo! It's very helpful :) 
I am not so good in java, and I am (believe it or not) still learning it. But this is a very useful repo and did help me quite a bit. It also did inspire me to make templates more in Java.

Regards!

**Comment by loneicewolf** [comment]
Also, this can be closed(if wanted, Just wanted to include this)
*Wishes from Sweden!*
`//Will.`

**Comment by LLLgoyour** [comment]
You are welcome! It's awesome to hear my repo is helpful and inspring for you, and I'm really glad with your appreciation! Feel free to share any suggestions with me, and hope you have a fun time learning it.

_Wishes from the US/China, 
Shinonome_
